name: go vet test

on:
  pull_request:
  push:
    branches:
      - main
      - homework-1

jobs:

  statictest:
    strategy:
      matrix:
        go-version: [1.16.x]
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download devopstest binary
      run: |
        mkdir $GITHUB_WORKSPACE/.tools
        cd $GITHUB_WORKSPACE/.tools
        wget https://github.com/Yandex-Practicum/go-autotests-bin/raw/main/.tools/devopstest 

    - name: Setup autotest binary
      run: |
        chmod -R +x $GITHUB_WORKSPACE/.tools/statictest
        mv $GITHUB_WORKSPACE/.tools/statictest /usr/local/bin/statictest

    - name: Run statictest
      run: |
        go vet -vettool=$(which statictest) ./...
